/**
 * build.js — Vercel build step
 *
 * Reads the BACKEND_URL environment variable (set in Vercel dashboard per environment)
 * and writes frontend/static/config.js with the resolved value.
 *
 * This file is intentionally vanilla Node.js (no npm dependencies) so it runs
 * on any platform without `npm install`.
 *
 * When you migrate to Vite/Next.js (shadcn/ui), replace this file with
 * VITE_BACKEND_URL or NEXT_PUBLIC_BACKEND_URL in your framework config.
 */

const fs = require('fs');
const path = require('path');

const backendUrl = process.env.BACKEND_URL || 'http://localhost:8000';

const content = `// AUTO-GENERATED by frontend/build.js — do not edit manually.
// To change this value set the BACKEND_URL environment variable in Vercel.
window.APP_CONFIG = {
  API_BASE_URL: "${backendUrl}"
};
`;

const outputPath = path.join(__dirname, 'static', 'config.js');
fs.writeFileSync(outputPath, content, 'utf8');

console.log(`[build.js] config.js written — API_BASE_URL = ${backendUrl}`);
