"""add unique constraint to vendas

Revision ID: 7a928158b3c6
Revises: 20260415_01
Create Date: 2026-04-16 19:51:25.083729
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from backend.app.database.session import DB_SCHEMA


# revision identifiers, used by Alembic.
revision = '7a928158b3c6'
down_revision = '20260415_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_venda_data_loja_produto', 'vendas', ['data', 'id_loja', 'id_produto'], schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_venda_data_loja_produto', 'vendas', type_='unique', schema=DB_SCHEMA)
    # ### end Alembic commands ###
